<a href="https://colab.research.google.com/github/Plumz17/FinalProjectML/blob/main/FinalProjectML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Machine Learning Final Project - Depression Existence Prediction Model
Description: In this project, we build a machine learning model to predict the existence of depression among students based on various academic, lifestyle, and psychological factors.
The dataset used is the **Student Depression Dataset** sourced from Kaggle in the following link: https://www.kaggle.com/datasets/hopesb/student-depression-dataset,
which contains responses from students regarding their mental health status.
This project was made by Group 6:
*   Anders Emmanuel Tan (24/541351/PA/22964)
*   Dhimas Early Oceandy (24/533508/PA/22584)
*   Azhar Maulana (24/533487/PA/22582)
*   Evan Razzan Adytaputra (24/545257/PA/23166)

## 0. Setting Up
Description: For this first section, we will be preparing the data that will later be processed. Since the uploaded files in Google Colab are only available in the runtime, I will be attaining those files by cloning them from the Github Repository. Additionaly, we will also be importing the libaries that we will be using for this submission to process the images.

In [30]:
# Cloning Github Repository to get the data files
!rm -rf FinalProjectML
!git clone https://github.com/Plumz17/FinalProjectML

Cloning into 'FinalProjectML'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), 435.79 KiB | 2.33 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [31]:
# Import Important Libraries
import numpy as np
import pandas as pd

# Import Data Frame
df = pd.read_csv('FinalProjectML/Student Depression Dataset.csv')

df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

## 1. Data Preparation
Description: For this first section, we will be preparing the data that will later be processed. Since the uploaded files in Google Colab are only available in the runtime, I will be attaining those files by cloning them from the Github Repository. Additionaly, we will also be importing the libaries that we will be using for this submission to process the images.

In [45]:
# Data Exploration
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 39 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27901 non-null  int64
 1   Age                                    27901 non-null  float64
 2   Academic Pressure                      27901 non-null  float64
 3   CGPA                                   27901 non-null  float64
 4   Study Satisfaction                     27901 non-null  float64
 5   Sleep Duration                         27901 non-null  int64
 6   Dietary Habits                         27901 non-null  int64
 7   Have you ever had suicidal thoughts ?  27901 non-null  int64
 8   Work/Study Hours                       27901 non-null  float64
 9   Financial Stress                       27901 non-null  float64
 10  Family History of Mental Illness       27901 non-null  int64
 11  Depression                             27901 non-null  int64
 12  Degree_B.Com                           27901 non-null  float64
 13  Degree_B.Ed                            27901 non-null  float64
 14  Degree_B.Pharm                         27901 non-null  float64
 15  Degree_B.Tech                          27901 non-null  float64
 16  Degree_BA                              27901 non-null  float64
 17  Degree_BBA                             27901 non-null  float64
 18  Degree_BCA                             27901 non-null  float64
 19  Degree_BE                              27901 non-null  float64
 20  Degree_BHM                             27901 non-null  float64
 21  Degree_BSc                             27901 non-null  float64
 22  Degree_Class 12                        27901 non-null  float64
 23  Degree_LLB                             27901 non-null  float64
 24  Degree_LLM                             27901 non-null  float64
 25  Degree_M.Com                           27901 non-null  float64
 26  Degree_M.Ed                            27901 non-null  float64
 27  Degree_M.Pharm                         27901 non-null  float64
 28  Degree_M.Tech                          27901 non-null  float64
 29  Degree_MA                              27901 non-null  float64
 30  Degree_MBA                             27901 non-null  float64
 31  Degree_MBBS                            27901 non-null  float64
 32  Degree_MCA                             27901 non-null  float64
 33  Degree_MD                              27901 non-null  float64
 34  Degree_ME                              27901 non-null  float64
 35  Degree_MHM                             27901 non-null  float64
 36  Degree_MSc                             27901 non-null  float64
 37  Degree_Others                          27901 non-null  float64
 38  Degree_PhD                             27901 non-null  float64
dtypes: float64(33), int64(6)
memory usage: 8.3 MB

Empty DataFrame
Columns: [Gender, Age, Academic Pressure, CGPA, Study Satisfaction, Sleep Duration, Dietary Habits, Have you ever had suicidal thoughts ?, Work/Study Hours, Financial Stress, Family History of Mental Illness, Depression, Degree_B.Com, Degree_B.Ed, Degree_B.Pharm, Degree_B.Tech, Degree_BA, Degree_BBA, Degree_BCA, Degree_BE, Degree_BHM, Degree_BSc, Degree_Class 12, Degree_LLB, Degree_LLM, Degree_M.Com, Degree_M.Ed, Degree_M.Pharm, Degree_M.Tech, Degree_MA, Degree_MBA, Degree_MBBS, Degree_MCA, Degree_MD, Degree_ME, Degree_MHM, Degree_MSc, Degree_Others, Degree_PhD]
Index: []

[0 rows x 39 columns]

In [46]:
# Check for NaN values
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Gender, Age, Academic Pressure, CGPA, Study Satisfaction, Sleep Duration, Dietary Habits, Have you ever had suicidal thoughts ?, Work/Study Hours, Financial Stress, Family History of Mental Illness, Depression, Degree_B.Com, Degree_B.Ed, Degree_B.Pharm, Degree_B.Tech, Degree_BA, Degree_BBA, Degree_BCA, Degree_BE, Degree_BHM, Degree_BSc, Degree_Class 12, Degree_LLB, Degree_LLM, Degree_M.Com, Degree_M.Ed, Degree_M.Pharm, Degree_M.Tech, Degree_MA, Degree_MBA, Degree_MBBS, Degree_MCA, Degree_MD, Degree_ME, Degree_MHM, Degree_MSc, Degree_Others, Degree_PhD]
Index: []

[0 rows x 39 columns]

In [33]:
# Check suspicous columns
print(df['Work Pressure'].value_counts())
print(df['Job Satisfaction'].value_counts())

Work Pressure
0.0    27898
5.0        2
2.0        1
Name: count, dtype: int64
Job Satisfaction
0.0    27893
2.0        3
4.0        2
1.0        2
3.0        1
Name: count, dtype: int64

In [34]:
# Drop irrelevant Columnns
df.drop(columns=['id', 'City', 'Profession', 'Work Pressure', "Job Satisfaction"], inplace=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27901 non-null  object
 1   Age                                    27901 non-null  float64
 2   Academic Pressure                      27901 non-null  float64
 3   CGPA                                   27901 non-null  float64
 4   Study Satisfaction                     27901 non-null  float64
 5   Sleep Duration                         27901 non-null  object
 6   Dietary Habits                         27901 non-null  object
 7   Degree                                 27901 non-null  object
 8   Have you ever had suicidal thoughts ?  27901 non-null  object
 9   Work/Study Hours                       27901 non-null  float64
 10  Financial Stress                       27898 non-null  float64
 11  Family History of Mental Illness       27901 non-null  object
 12  Depression                             27901 non-null  int64
dtypes: float64(6), int64(1), object(6)
memory usage: 2.8+ MB

In [36]:
# Binary Columns Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

binary_cols = [
  'Gender',
  'Have you ever had suicidal thoughts ?',
  'Family History of Mental Illness'
]

for col in binary_cols:
  df[col] = le.fit_transform(df[col])

df[binary_cols].head()

,Gender,Have you ever had suicidal thoughts ?,Family History of Mental Illness
0,1,1,0
1,0,0,1
2,1,0,1
3,0,1,1
4,0,1,0

In [37]:
# Ordinal Columns Label Encoding
sleep_map = {
  'Less than 5 hours': 0,
  '5-6 hours': 1,
  '7-8 hours': 2,
  'More than 8 hours': 3,
  'Others': 3 # merge with the fewest category
}
diet_map = {
  'Unhealthy': 0,
  'Moderate': 1,
  'Healthy': 2,
  'Others': 2 # merge with the fewest category
}
df['Sleep Duration'] = df['Sleep Duration'].map(sleep_map)
df['Dietary Habits'] = df['Dietary Habits'].map(diet_map)
df[['Sleep Duration', 'Dietary Habits']].head()

   Sleep Duration  Dietary Habits
0               1               2
1               1               1
2               0               2
3               2               1
4               1               1

In [39]:
# Fill NaN values with median
df = df.fillna(df.median(numeric_only=True))

In [41]:
# Nominal Columns Label Encoding using One Hot Encoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe = OneHotEncoder(sparse_output=False, drop='first')
degree_encoded = ohe.fit_transform(df[['Degree']])
degree_cols = ohe.get_feature_names_out(['Degree'])
degree_df = pd.DataFrame(degree_encoded, columns=degree_cols, index=df.index)
df = pd.concat([df.drop(columns=['Degree']), degree_df], axis=1)

# Verify results
df.filter(like='Degree').head()

,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,Degree_BSc,...,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_Others,Degree_PhD
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
# Train, Validation, Test split
from sklearn.model_selection import train_test_split

X = df.drop(columns=["Depression"])
y = df["Depression"]

# First Split (Data Frame into Train and temp)
X_train, X_temp, y_train, y_temp = train_test_split(
  X,
  y,
  test_size=0.30, # Train: 70%, Temp: 30%
  stratify=y,
  random_state=42
)

# Second Split (temp into Validation and Test)
X_val, X_test, y_val, y_test = train_test_split(
  X_temp,
  y_temp,
  test_size=0.50, # Validation: 15%, Test: 15%
  stratify=y_temp,
  random_state=42
)

print("Training set (70%)")
print(y_train.value_counts())

print("\nValidation set (15%)")
print(y_val.value_counts())

print("\nTest set (15%)")
print(y_test.value_counts())

Training set (70%)
Depression
1    11435
0     8095
Name: count, dtype: int64

Validation set (15%)
Depression
1    2450
0    1735
Name: count, dtype: int64

Test set (15%)
Depression
1    2451
0    1735
Name: count, dtype: int64

## 2. Modelling
Description: For this section, we will be training the machine learning models using the data that we have prepared in the previous section. As for the models, we will compare the performance of several different machine learning models to determine which one yields the best result. The following are the models that we use: Logistic Regression, Naive Bayes, kNN, SVM, Decision Tree, Random Forest, and XGBoost.

In [43]:
print('#PlumzPlummeted')

#PlumzPlummeted

In [44]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
  accuracy_score,
  precision_score,
  recall_score,
  f1_score,
  classification_report
)

models = {
  "Logistic Regression": Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, random_state=42))
  ]),

  "Naive Bayes": Pipeline([
    ("scaler", StandardScaler()),
    ("model", GaussianNB())
  ]),

  "kNN": Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier(n_neighbors=5))
  ]),
  "SVM": Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC(kernel='rbf', random_state=42))
  ]),
  "Decision Tree": Pipeline([
    ("model", DecisionTreeClassifier(random_state=42))
  ]),
  "Random Forest": Pipeline([
    ("model", RandomForestClassifier(
      n_estimators=100,
      random_state=42
    ))
  ]),
  "XGBoost": Pipeline([
    ("model", XGBClassifier(
      eval_metric='logloss',
      random_state=42
    ))
  ])
}

for name, model in models.items():
  print(f"\n========== {name} ==========")

  # Train
  model.fit(X_train, y_train)

  # Predict on validation set
  y_pred = model.predict(X_val)

  # Evaluation Metrics
  accuracy = accuracy_score(y_val, y_pred)
  precision = precision_score(y_val, y_pred)
  recall = recall_score(y_val, y_pred)
  f1 = f1_score(y_val, y_pred)

  print(f"Accuracy : {accuracy:.4f}")
  print(f"Precision: {precision:.4f}")
  print(f"Recall   : {recall:.4f}")
  print(f"F1-Score : {f1:.4f}")

  print("\nClassification Report:")
  print(classification_report(y_val, y_pred))

========== Logistic Regression ==========
Accuracy : 0.8507
Precision: 0.8608
Recall   : 0.8886
F1-Score : 0.8745

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.80      0.82      1735
           1       0.86      0.89      0.87      2450

    accuracy                           0.85      4185
   macro avg       0.85      0.84      0.85      4185
weighted avg       0.85      0.85      0.85      4185


========== Naive Bayes ==========
Accuracy : 0.7551
Precision: 0.7907
Recall   : 0.7910
F1-Score : 0.7909

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.70      0.70      1735
           1       0.79      0.79      0.79      2450

    accuracy                           0.76      4185
   macro avg       0.75      0.75      0.75      4185
weighted avg       0.76      0.76      0.76      4185


========== kNN ==========
Accuracy : 0.8105
Precision: 0.8151
Recall   : 0.8747
F1-Score : 0.8439

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.72      0.76      1735
           1       0.82      0.87      0.84      2450

    accuracy                           0.81      4185
   macro avg       0.81      0.80      0.80      4185
weighted avg       0.81      0.81      0.81      4185


========== SVM ==========
Accuracy : 0.8483
Precision: 0.8524
Recall   : 0.8959
F1-Score : 0.8736

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.78      0.81      1735
           1       0.85      0.90      0.87      2450

    accuracy                           0.85      4185
   macro avg       0.85      0.84      0.84      4185
weighted avg       0.85      0.85      0.85      4185


========== Decision Tree ==========
Accuracy : 0.7866
Precision: 0.8197
Recall   : 0.8147
F1-Score : 0.8172

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.75      0.74      1735
           1       0.82      0.81      0.82      2450

    accuracy                           0.79      4185
   macro avg       0.78      0.78      0.78      4185
weighted avg       0.79      0.79      0.79      4185


========== Random Forest ==========
Accuracy : 0.8454
Precision: 0.8539
Recall   : 0.8878
F1-Score : 0.8705

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.79      0.81      1735
           1       0.85      0.89      0.87      2450

    accuracy                           0.85      4185
   macro avg       0.84      0.84      0.84      4185
weighted avg       0.84      0.85      0.84      4185


========== XGBoost ==========
Accuracy : 0.8425
Precision: 0.8510
Recall   : 0.8861
F1-Score : 0.8682

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.78      0.80      1735
           1       0.85      0.89      0.87      2450

    accuracy                           0.84      4185
   macro avg       0.84      0.83      0.84      4185
weighted avg       0.84      0.84      0.84      4185

## 3. Evaluation
Description:

In [ ]:
## 4. Entering a new data
Description: